const baseRule = {
  'no-new': 'off',
  camelcase: 'off',
  'no-return-assign': 'off',
  indent: 'off',
  'comma-dangle': 'off',
  'space-before-function-paren': 'off',
  semi: 'off',
  'object-curly-spacing': 'off',
  quotes: 'off',
  'no-var': 'off',
  curly: 'off',
  'no-sequences': 'off',
  'no-unused-expressions': 'off',
  yoda: 'off',
  'no-void': 'off',
  'one-var': 'off',
  'no-extra-parens': 'off',
  'block-spacing': 'off',
  'object-curly-newline': 'off',
  'new-cap': 'off',
  'wrap-iife': 'off',
  'no-trailing-spaces': 'off',
  'no-fallthrough': 'off',
  eqeqeq: 'off',
  'require-atomic-updates': ['warn', { allowProperties: true }],
  'no-prototype-builtins': 'warn',
  'no-multiple-empty-lines': 'off',
  'no-unused-vars': 'warn',
  'no-use-before-define': 'off',
  'comma-spacing': 'off',
  'no-mixed-operators': 'off',
  'operator-linebreak': 'off',
  'no-func-assign': 'warn',
  'no-undef': 'warn',
  'promise/param-names': 'off',
  'no-throw-literal': 'warn',
  'no-redeclare': 'warn',
  'space-before-blocks': 'off',
  'new-parens': 'off',
  'no-useless-call': 'warn',
  'brace-style': 'off',
  'space-unary-ops': 'off',
  'no-unreachable': 'warn',
  'no-new-func': 'warn',
  'no-control-regex': 'warn',
  'comma-style': 'off',
  'space-in-parens': 'off',
  'object-property-newline': 'off',
  'quote-props': 'off',
  'eol-last': 'off',
  'no-multi-spaces': 'off',
  'padded-blocks': 'off',
  'import/first': 'off',
  'import/no-duplicates': 'warn',
  'no-useless-return': 'off',
  'object-shorthand': 'off',
  'no-async-promise-executor': 'warn',
  'no-unneeded-ternary': 'off',
  'no-unmodified-loop-condition': 'warn',
  'prefer-const': 'off',
  'no-labels': 'off',
  'multiline-ternary': 'off',
}

const typescriptRule = {
  ...baseRule,
  'no-undef': 'off',
  'no-redeclare': 'off',
  'no-unused-vars': 'off',
  '@typescript-eslint/indent': 'off',
  '@typescript-eslint/comma-dangle': 'off',
  '@typescript-eslint/semi': 'off',
  '@typescript-eslint/object-curly-spacing': 'off',
  '@typescript-eslint/quotes': 'off',
  '@typescript-eslint/member-delimiter-style': 'off',
  '@typescript-eslint/promise-function-async': 'off',
  '@typescript-eslint/block-spacing': 'off',
  '@typescript-eslint/prefer-optional-chain': 'off',
  '@typescript-eslint/no-unnecessary-type-assertion': 'off',
  '@typescript-eslint/prefer-nullish-coalescing': 'off',
  '@typescript-eslint/array-type': 'off',
  '@typescript-eslint/prefer-ts-expect-error': 'off',
  '@typescript-eslint/no-confusing-void-expression': 'off',
  '@typescript-eslint/consistent-type-assertions': 'off',
  '@typescript-eslint/no-var-requires': 'off',
  '@typescript-eslint/no-unused-vars': 'warn',
  '@typescript-eslint/no-floating-promises': 'warn',
  '@typescript-eslint/no-dynamic-delete': 'off',
  '@typescript-eslint/consistent-generic-constructors': 'off',
  '@typescript-eslint/prefer-includes': 'off',
  '@typescript-eslint/lines-between-class-members': 'off',
  '@typescript-eslint/prefer-readonly': 'off',
  '@typescript-eslint/consistent-type-imports': 'off',
  '@typescript-eslint/no-invalid-void-type': 'off',
  '@typescript-eslint/consistent-indexed-object-style': 'off',
  '@typescript-eslint/no-base-to-string': 'warn',
  '@typescript-eslint/unbound-method': 'warn',
  '@typescript-eslint/strict-boolean-expressions': 'off',
  '@typescript-eslint/explicit-function-return-type': 'off',
  '@typescript-eslint/space-before-function-paren': 'off',
  '@typescript-eslint/no-non-null-assertion': 'off',
  '@typescript-eslint/restrict-template-expressions': [
    1,
    {
      allowBoolean: true,
      allowAny: true,
    },
  ],
  '@typescript-eslint/restrict-plus-operands': [
    1,
    {
      allowBoolean: true,
      allowAny: true,
    },
  ],
  '@typescript-eslint/no-misused-promises': [
    'error',
    {
      checksVoidReturn: {
        arguments: false,
        attributes: false,
      },
    },
  ],
  '@typescript-eslint/naming-convention': 'off',
  '@typescript-eslint/return-await': 'off',
  '@typescript-eslint/ban-ts-comment': 'off',
  '@typescript-eslint/no-unsafe-argument': 'off',
}

const vueRule = {
  ...baseRule,
  'vue/multi-word-component-names': 'off',
  'vue/max-attributes-per-line': 'off',
  'vue/singleline-html-element-content-newline': 'off',
  'vue/use-v-on-exact': 'off',
  'vue/html-closing-bracket-newline': 'off',
  'vue/html-closing-bracket-spacing': 'off',
  'vue/attributes-order': 'off',
  'vue/order-in-components': 'off',
  'vue/attribute-hyphenation': 'off',
  'vue/no-unused-vars': 'warn',
  'no-self-compare': 'warn',
}

exports.base = {
  extends: ['standard'],
  rules: baseRule,
}

exports.html = {
  files: ['*.html'],
  plugins: ['html'],
}

exports.typescript = {
  files: ['*.ts'],
  rules: typescriptRule,
  parser: '@typescript-eslint/parser',
  extends: ['standard-with-typescript'],
}

exports.vue = {
  files: ['*.vue'],
  rules: vueRule,
  parser: 'vue-eslint-parser',
  extends: [
    'standard',
    'plugin:vue/base',
    'plugin:vue/vue3-recommended',
    'plugin:vue-pug/vue3-recommended',
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    parser: {
      js: 'espree',
      ts: '@typescript-eslint/parser',
    },
  },
}
